theme: jekyll-theme-tactile
title: BLE-UAE
       (Understand 
       and Exploiting)
description: Bluetooth Devices recon and exploitation!
logo: photos/bleah.png
show_downloads: false
google_analytics: UA-89542956-2
