theme: jekyll-theme-dinky
title: BLE-UAE
       (Understanding and Exploitation)
homepage : BLE-UAE(Understanding and Exploitation)
description: Bluetooth Devices recon and exploitation!
logo: photos/bleah.png
google_analytics: UA-89542956-2
